language: python
python:
- 2.7
- 2.6

install:
 - sudo apt-get install python-biopython

script:
 - bash test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
notifications:
   email:
     - magnus@genesilico.pl